# Generated by Django 4.0.3 on 2022-04-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allusers',
            fields=[
                ('username', models.CharField(max_length=16, unique=True)),
                ('phoneno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'allusers',
                'managed': True,
            },
        ),
    ]
