--INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('pmacgilfoyle1a','kdaout18',48,87,'delivery','pending');
--INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('eskamal17','dmein13',45,7,'delivery','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('dwallbridge9','wratchfordo',33,70,'delivery','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('mlawrey1j','nzannollij',17,60,'self pickup','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('wgallys','msodeau16',40,50,'self pickup','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('nshreeves1l','nhourstan10',19,70,'delivery','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('rparmeter6','dbodycombe1f',15,99,'delivery','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('lmiddletonu','dbodycombe1f',24,79,'delivery','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('eskamal17','dmein13',34,72,'delivery','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('wgallys','rdysartn',12,17,'self pickup','pending');
--INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('lfontenotg','lmiddletonu',47,95,'self pickup','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('lgaddas1','kpatridge11',21,12,'delivery','pending');
--INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('lshreve15','dwallbridge9',50,95,'self pickup','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('lfontenotg','mlawrey1j',20,34,'delivery','pending');
--INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('cfiginp','ejulyanr',43,44,'delivery','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('mlomaxy','nhourstan10',19,59,'self pickup','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('eskamal17','wratchfordo',25,21,'self pickup','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('jmatisset','rdysartn',12,60,'delivery','pending');
--INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('mchampain1c','dledgerl',41,34,'delivery','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('ejulyanr','dbodycombe1f',24,13,'delivery','pending');
